### PR TITLE
topic similarity

### PR DESCRIPTION
**Pull request by f-hafner**
compute cosine similarity between
- topics as a student and as a publishing researcher
- topics as a student/researcher and set of employers (carnegie institutions)
   - similarity to average faculty (sum of topics across all faculty members)
   - similarity to closest collaborator

Extend other functions
- enumerated_inputs: move to src/dataprep/helpers/functions.py; add option for limiting the number of elements yielded.

### CODE REVIEW

**Comment by f-hafner** [comment]
some records are missing in the final table. need to investigate

**Review by chrished — APPROVED** [review]
did not find any mistakes. 

The constant in the division for the cosine similarity should be innocent as the numerator should be 0 always if the denominator can be 0.

**Comment by chrished** [comment]
The missings: are these missing because there is no overlap in topics in a particular pair?

**Comment by f-hafner** [comment]
> The missings: are these missing because there is no overlap in topics in a particular pair?

if you mean this:


> some records are missing in the final table. need to investigate

-- they should not be missing, and I need to understand why they are missing from the database

**Comment by chrished** [comment]
Yes that’s what I meant, okay! Am 2023-03-09 um 20:09 schrieb f-hafner ***@***.***>:﻿

The missings: are these missing because there is no overlap in topics in a particular pair?

if you mean this:

some records are missing in the final table. need to investigate

-- they should not be missing, and I need to understand why they are missing from the database

**Pull request merged**
